
package com.pd.monitor.mobileCode;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileInfoSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileInfoSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWorld", action = "http://tempuri.org/HelloWorld")
    @WebResult(name = "HelloWorldResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "HelloWorld", targetNamespace = "http://tempuri.org/", className = "mobileCode.HelloWorld")
    @ResponseWrapper(localName = "HelloWorldResponse", targetNamespace = "http://tempuri.org/", className = "mobileCode.HelloWorldResponse")
    public String helloWorld();

    /**
     * 
     * @param filename
     * @param sbid
     * @return
     *     returns mobileCode.RetClass
     */
    @WebMethod(operationName = "GetPlayUrl", action = "http://tempuri.org/GetPlayUrl")
    @WebResult(name = "GetPlayUrlResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPlayUrl", targetNamespace = "http://tempuri.org/", className = "mobileCode.GetPlayUrl")
    @ResponseWrapper(localName = "GetPlayUrlResponse", targetNamespace = "http://tempuri.org/", className = "mobileCode.GetPlayUrlResponse")
    public RetClass getPlayUrl(
        @WebParam(name = "sbid", targetNamespace = "http://tempuri.org/")
        String sbid,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename);

    /**
     * 
     * @param filename
     * @param sbid
     * @return
     *     returns mobileCode.RetClass
     */
    @WebMethod(operationName = "TestFile", action = "http://tempuri.org/TestFile")
    @WebResult(name = "TestFileResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "TestFile", targetNamespace = "http://tempuri.org/", className = "mobileCode.TestFile")
    @ResponseWrapper(localName = "TestFileResponse", targetNamespace = "http://tempuri.org/", className = "mobileCode.TestFileResponse")
    public RetClass testFile(
        @WebParam(name = "sbid", targetNamespace = "http://tempuri.org/")
        String sbid,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename);

    /**
     * 
     * @param filename
     * @param fileData
     * @param sbid
     * @return
     *     returns mobileCode.RetClass
     */
    @WebMethod(operationName = "UpFileData", action = "http://tempuri.org/UpFileData")
    @WebResult(name = "UpFileDataResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpFileData", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpFileData")
    @ResponseWrapper(localName = "UpFileDataResponse", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpFileDataResponse")
    public RetClass upFileData(
        @WebParam(name = "sbid", targetNamespace = "http://tempuri.org/")
        String sbid,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename,
        @WebParam(name = "fileData", targetNamespace = "http://tempuri.org/")
        byte[] fileData);

    /**
     * 
     * @param gpsData
     * @param filename
     * @param fileData
     * @param sbid
     * @return
     *     returns mobileCode.RetClass
     */
    @WebMethod(operationName = "UpFileDataGps", action = "http://tempuri.org/UpFileDataGps")
    @WebResult(name = "UpFileDataGpsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpFileDataGps", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpFileDataGps")
    @ResponseWrapper(localName = "UpFileDataGpsResponse", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpFileDataGpsResponse")
    public RetClass upFileDataGps(
        @WebParam(name = "sbid", targetNamespace = "http://tempuri.org/")
        String sbid,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename,
        @WebParam(name = "fileData", targetNamespace = "http://tempuri.org/")
        byte[] fileData,
        @WebParam(name = "gpsData", targetNamespace = "http://tempuri.org/")
        String gpsData);

    /**
     * 
     * @param msg
     * @param code
     * @param sbid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpState", action = "http://tempuri.org/UpState")
    @WebResult(name = "UpStateResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpState", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpState")
    @ResponseWrapper(localName = "UpStateResponse", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpStateResponse")
    public String upState(
        @WebParam(name = "sbid", targetNamespace = "http://tempuri.org/")
        String sbid,
        @WebParam(name = "code", targetNamespace = "http://tempuri.org/")
        String code,
        @WebParam(name = "msg", targetNamespace = "http://tempuri.org/")
        String msg);

    /**
     * 
     * @param msg
     * @param filename
     * @param sbid
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpGroup", action = "http://tempuri.org/UpGroup")
    @WebResult(name = "UpGroupResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpGroup", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpGroup")
    @ResponseWrapper(localName = "UpGroupResponse", targetNamespace = "http://tempuri.org/", className = "mobileCode.UpGroupResponse")
    public String upGroup(
        @WebParam(name = "sbid", targetNamespace = "http://tempuri.org/")
        String sbid,
        @WebParam(name = "filename", targetNamespace = "http://tempuri.org/")
        String filename,
        @WebParam(name = "msg", targetNamespace = "http://tempuri.org/")
        String msg);

}
